<?php

return [

    'table_names' => [
        'users' => 'users',
        'almacenes' => 'almacenes',
        'familia_cliente' => 'familia_cliente',
        'familia_producto' => 'familia_producto',
        'proveedores' => 'proveedores',
        'compras' => 'compras',
        'compra_almacen' => 'compra_almacen',
        'compra_proveedor' => 'compra_proveedor',
        'conceptos' => 'conceptos',
        'config' => 'config',
        'cuentas_por_cobrar' => 'cuentas_por_cobrar',
        'cuenta_por_cobrar_user' => 'cuenta_por_cobrar_user',
        'empresas' => 'empresas',
        'ingresos' => 'ingresos',
        'ingreso_user' => 'ingreso_user',
        'ingreso_cuenta_por_cobrar' => 'ingreso_cuenta_por_cobrar',
        'medidas' => 'medidas',
        'productos' => 'productos',
        'almacen_producto' => 'almacen_producto',
        'familia_producto_producto' => 'familia_producto_producto',
        'medida_producto' => 'medida_producto',
        'paquetes' => 'paquetes',
        'paquete_user' => 'paquete_user',
        'paquete_detalle' => 'paquete_detalle',
        'paquete_detalle_paquete' => 'paquete_detalle_paquete',
        'paquete_detalle_producto' => 'paquete_detalle_producto',
        'paquete_detalle_medida' => 'paquete_detalle_medida',
        'pedidos' => 'pedidos',
        'pedido_detalle' => 'pedido_detalles',
        'pedido_user' => 'pedido_user',
        'pedido_paquete' => 'pedido_paquete',
        'pedido_detalle_pedido' => 'pedido_detalle_pedido',
        'pedido_detalle_user' => 'pedido_detalle_user',
        'pedido_detalle_producto' => 'pedido_detalle_producto',
        'pedido_detalle_medida' => 'pedido_detalle_medida',
        'movimientos' => 'movimientos',
        'movimiento_user' => 'movimiento_user',
        'movimiento_compra' => 'movimiento_compra',
        'movimiento_producto' => 'movimiento_producto',
        'movimiento_proveedor' => 'movimiento_proveedor',
        'movimiento_pedido' => 'movimiento_pedido',
        'movimiento_almacen' => 'movimiento_almacen',
        'movimiento_medida' => 'movimiento_medida',
    ],

    ];
